id: produceFlame
type: Activity
name: Produce Flame
tags: [conjuration, cantrip, druid, attackSpell, damageSpell, fireDamage]
time: bonus action
range: self
duration: 10 minutes
description: |
  A flickering flame appears in your hand and remains there for the duration. While there, the flame emits no heat and ignites nothing, and it sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. The spell ends if you cast it again.

  Until the spell ends, you can take a Magic action to hurl fire at a creature or an object within 60 feet of you. Make a $(formatBonus(attributes.spellcasting.attack)) ranged spell attack. On a hit, the target takes $(meta.level >= 17 ? 4 : meta.level >= 11 ? 3 : meta.level >= 5 ? 2 : 1)d8 Fire damage.

